language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email: false
  irc:
    channels:
      - "irc.spi.gt#techcable"
script: mvn clean package
cache:
  directories:
    - '$HOME/.m2/repository'
