name: ${project.name}
version: ${project.version}
author: DSH105
description: Mobs Under Your Control
website: ${project.url}
main: ${main.class}
commands:
    ecupdate:
        description: Update the EchoPet plugin.